"""Add thumbnail column

Revision ID: b111cb8a535b
Revises: d29782cbd194
Create Date: 2025-05-18 16:48:03.961071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b111cb8a535b'
down_revision = 'd29782cbd194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_column('views')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.INTEGER(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
